<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Aaron-Laptop" name="Default test" tests="8" failures="1" timestamp="6 Jan 2016 21:43:17 GMT" time="0.056" errors="0">
  <testcase name="testAdd" time="0.028" classname="test.testCalculator">
    <failure type="java.util.NoSuchElementException">
      <![CDATA[java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Unknown Source)
	at java.util.Scanner.next(Unknown Source)
	at calculator.Calculator.getUserInput(Calculator.java:53)
	at calculator.Calculator.add(Calculator.java:157)
	at calculator.Calculator.getUserInput(Calculator.java:56)
	at calculator.Calculator.add(Calculator.java:157)
	at calculator.Calculator.getUserInput(Calculator.java:56)
	at calculator.Calculator.add(Calculator.java:157)
	at calculator.Calculator.getUserInput(Calculator.java:56)
	at calculator.Calculator.add(Calculator.java:157)
	at calculator.Calculator.getUserInput(Calculator.java:56)
	at test.testCalculator.testAdd(testCalculator.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- testAdd -->
  <testcase name="testClear" time="0.001" classname="test.testCalculator"/>
  <testcase name="testDiv" time="0.001" classname="test.testCalculator"/>
  <testcase name="testHist" time="0.001" classname="test.testCalculator"/>
  <testcase name="testMult" time="0.001" classname="test.testCalculator"/>
  <testcase name="testReuse" time="0.001" classname="test.testCalculator"/>
  <testcase name="testSub" time="0.001" classname="test.testCalculator"/>
  <testcase name="testWumbo" time="0.001" classname="test.testCalculator"/>
</testsuite> <!-- Default test -->
